defaults:
  - _self_
  - dataset: null
  - model: null
  - experiment: ${model}_${dataset}

expname: ???
checkpoint:
cond_mask: uncond
task: uncond
lex_order: False
load_bbox:
ode_solver: euler
DM_model: 
  _target_: diffusers.schedulers.DDIMScheduler
small: False
device: 0
calc_miou: False
multirun: False
visualize: True
logdir: ./wandb
instance_idx: 4
seed: 42
explain: True
target_idx: 6
target_attr: position
ig_return_xy: True
dataset_name: ${hydra:runtime.choices.dataset}

hydra:  
  output_subdir: null  
  run:  
    dir: .